name: flow

dependencies:
    - python==3.7.3
    - pip:
        - scipy
        - lxml
        - six
        - path.py
        - python-dateutil
        - pip
        - tensorflow
        - setuptools
        - plotly
        - gym
        - pyprind
        - nose2
        - cached_property
        - joblib
        - python3-distutils
        - libfreetype6-dev
        - libpng-dev
        - matplotlib
        - dill
        - lz4
        - ray
        - setproctitle
        - psutil
        - opencv-python
        - boto3
        - redis
